# Generated by Django 2.1.3 on 2019-08-14 17:50

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
