# Generated by Django 2.1.3 on 2019-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_projectdetail_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('contact_nos', models.PositiveIntegerField(max_length=10)),
                ('message', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
    ]
