# Generated by Django 2.1.3 on 2019-08-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_customerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='contact_nos',
            field=models.PositiveIntegerField(),
        ),
    ]
