# Generated by Django 2.1.3 on 2019-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20190817_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
