# Generated by Django 2.1.3 on 2019-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20190817_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
